import { ISLAND_SCALE } from './worldConfig.js'

// Species arrival schedule — each entry arrives when readyWhen() returns true.
// Only the FIRST un-arrived species is ever evaluated; arrivals are strictly sequential.
// enginePops = engine state pops (grass, fungi, tree counts)
// livePops   = live posMap counts written by the canvas RAF each frame (animals + trees)
export const ARRIVAL_SCHEDULE = [
  {
    spId:    'tree',
    count:   12,
    label:   'Fig Tree',
    trigger: 'island initialisation',
    message: 'The first Fig Trees have been planted. The rehabilitation of the island begins.',
    concept: 'Primary Producer',
    readyWhen:  () => true,
    progressOf: () => ({ current: 1, needed: 1, unit: 'ready' }),
  },
  {
    spId:    'grass',
    count:   80,
    label:   'Island Grass',
    trigger: 'trees spreading across the island',
    message: 'Grass seeds have blown in from the mainland, taking root across the plains.',
    concept: 'Primary Producer',
    overseerText:   'Island Grass has taken root. The plains are filling in. This is the second link in your food chain — primary producers. The trees were the first.\n\nHerbivores will need this. Do not let it die.',
    overseerSprite: 'neutral',
    readyWhen:  (enginePops, livePops) => (livePops.tree ?? 0) >= 30,
    progressOf: (enginePops, livePops) => ({ current: Math.round(livePops.tree ?? 0), needed: 30, unit: 'trees' }),
  },
  {
    spId:    'fungi',
    count:   40,
    label:   'Shelf Fungi',
    trigger: 'grass covering the plains',
    message: 'Fungi spores have settled in the forest, beginning to break down dead matter.',
    concept: 'Decomposer',
    overseerText:   'Shelf Fungi have arrived. They are decomposers — they break down dead organic matter and return nutrients to the soil.\n\nDecomposers are often overlooked. That is a mistake. Without them, the nutrient cycle collapses and nothing grows.',
    overseerSprite: 'neutral',
    readyWhen:  (enginePops, livePops) => (enginePops.grass ?? 0) >= 800,
    progressOf: (enginePops, livePops) => ({ current: Math.round(enginePops.grass ?? 0), needed: 800, unit: 'grass' }),
  },
  {
    spId:    'beetle',
    count:   28,
    label:   'Rock Beetle',
    trigger: 'fungi establishing in the forest',
    message: 'A swarm of beetles has colonised the island, drawn by the abundance of plant life.',
    concept: 'Primary Consumer',
    overseerText:   'Rock Beetles have colonised the island. Your first primary consumers — heterotrophs that eat plants instead of making their own energy.\n\nWatch the grass. Beetles eat a great deal of it.',
    overseerSprite: 'friendly',
    readyWhen:  (enginePops, livePops) => (enginePops.fungi ?? 0) >= 90,
    progressOf: (enginePops, livePops) => ({ current: Math.round(enginePops.fungi ?? 0), needed: 90, unit: 'fungi' }),
  },
  {
    spId:    'firefly',
    count:   18,
    label:   'Pond Firefly',
    trigger: 'insects colonising the island',
    message: 'Fireflies have appeared around the island\'s ponds, drawn by warm water and pond vegetation.',
    concept: 'Habitat Specialist',
    overseerText:   'Pond Fireflies have arrived. They live only around the ponds — a habitat specialist. Stray too far from water and they die.\n\nFrogs will eat them. Watch both populations.',
    overseerSprite: 'friendly',
    readyWhen:  (enginePops, livePops) => (livePops.beetle ?? 0) >= 60,
    progressOf: (enginePops, livePops) => ({ current: Math.round(livePops.beetle ?? 0), needed: 60, unit: 'beetles' }),
  },
  {
    spId:    'deer',
    count:   14,
    label:   'Leaf Deer',
    trigger: 'a thriving beetle population',
    message: 'A small herd of deer has crossed from a nearby island, seeking new grazing grounds.',
    concept: 'Herbivore Migration',
    overseerText:   'A herd of Leaf Deer has migrated to the island. Herbivores. They eat plants. Hawks will eat them.\n\nThis is the natural order of things. Your job is to make sure the chain does not break.',
    overseerSprite: 'neutral',
    readyWhen:  (enginePops, livePops) => (livePops.beetle ?? 0) >= 80,
    progressOf: (enginePops, livePops) => ({ current: Math.round(livePops.beetle ?? 0), needed: 80, unit: 'beetles' }),
  },
  {
    spId:    'frog',
    count:   20,
    label:   'Marsh Frog',
    trigger: 'the deer herd establishing',
    message: 'Frogs have appeared in the wetlands — carried by seasonal flood waters.',
    concept: 'Secondary Consumer',
    overseerText:   'Marsh Frogs have appeared in the wetlands. Secondary consumers — they eat the beetles that eat the plants.\n\nThe food web is taking shape. Each trophic level depends on the one below it.',
    overseerSprite: 'friendly',
    readyWhen:  (enginePops, livePops) => (livePops.deer ?? 0) >= 18,
    progressOf: (enginePops, livePops) => ({ current: Math.round(livePops.deer ?? 0), needed: 18, unit: 'deer' }),
  },
  {
    spId:    'boar',
    count:   12,
    label:   'Wild Boar',
    trigger: 'a stable frog colony',
    message: 'Wild boar have swum across to the island, attracted by roots and beetle grubs.',
    concept: 'Omnivore',
    overseerText:   'Wild Boar have arrived. Omnivores — they eat both plants and animals. They complicate the food web considerably.\n\nI mention this not to worry you, but because it is your problem now.',
    overseerSprite: 'neutral',
    readyWhen:  (enginePops, livePops) => (livePops.frog ?? 0) >= 14,
    progressOf: (enginePops, livePops) => ({ current: Math.round(livePops.frog ?? 0), needed: 14, unit: 'frogs' }),
  },
  {
    spId:    'monitor',
    count:   8,
    label:   'Monitor Lizard',
    trigger: 'boar roaming the island',
    message: 'Monitor lizards have drifted to the wetlands on floating debris from a storm.',
    concept: 'Tertiary Consumer',
    overseerText:   'Monitor Lizards have drifted in on storm debris. Tertiary predators. They hunt frogs, beetles, and wild boar — the only check on the boar population.\n\nDo not let them go extinct. They are load-bearing.',
    overseerSprite: 'neutral',
    readyWhen:  (enginePops, livePops) => (livePops.boar ?? 0) >= 10,
    progressOf: (enginePops, livePops) => ({ current: Math.round(livePops.boar ?? 0), needed: 10, unit: 'boar' }),
  },
  {
    spId:    'hawk',
    count:   4,
    label:   'Island Hawk',
    trigger: 'monitor lizards in the wetlands',
    message: 'A pair of hawks has arrived — apex predators now rule the skies.',
    concept: 'Apex Predator',
    overseerText:   'The Island Hawk has arrived. Apex predator. Nothing on this island will eat them.\n\nThey sit at the top of the food chain. Their population is small, but their impact is not. Lose them, and the entire system destabilises.\n\nI trust you understand the weight of that.',
    overseerSprite: 'threat',
    readyWhen:  (enginePops, livePops) => (livePops.monitor ?? 0) >= 5,
    progressOf: (enginePops, livePops) => ({ current: Math.round(livePops.monitor ?? 0), needed: 5, unit: 'monitors' }),
  },
]

// Approximate shore spawn centres per species (base 820×540 coords × ISLAND_SCALE)
// Animals "wash up" near the coast, wetland species near the wetland area.
export const ARRIVAL_HOME = {
  tree:    { x: 220 * ISLAND_SCALE, y: 210 * ISLAND_SCALE, spread: 55 * ISLAND_SCALE },
  beetle:  { x: 650 * ISLAND_SCALE, y: 420 * ISLAND_SCALE, spread: 80 * ISLAND_SCALE },
  deer:    { x: 630 * ISLAND_SCALE, y: 390 * ISLAND_SCALE, spread: 90 * ISLAND_SCALE },
  firefly: { x: 360 * ISLAND_SCALE, y: 310 * ISLAND_SCALE, spread: 50 * ISLAND_SCALE },  // pond area, main island
  frog:    { x: 360 * ISLAND_SCALE, y: 320 * ISLAND_SCALE, spread: 70 * ISLAND_SCALE },  // pond area, main island
  boar:    { x: 660 * ISLAND_SCALE, y: 430 * ISLAND_SCALE, spread: 80 * ISLAND_SCALE },
  monitor: { x: 550 * ISLAND_SCALE, y: 180 * ISLAND_SCALE, spread: 70 * ISLAND_SCALE },  // highland coast, main island
  hawk:    { x: 370 * ISLAND_SCALE, y: 120 * ISLAND_SCALE, spread: 70 * ISLAND_SCALE },
}
